import React, { useState } from "react";
import { ArrowIcon } from "@/icons/index";

type NewsletterProps = {};

const Newsletter: React.FC<NewsletterProps> = () => {
  const [nodes, setNodes] = useState("");
  const [isLoading, setLoading] = useState(true);

  return (
    <div
      id="mauticform_wrapper_websitenewslettersubscription"
      className="mauticform_wrapper"
    >
      <form
        autoComplete="false"
        role="form"
        method="post"
        action="https://mautic.int.ethswarm.org/form/submit?formId=4"
        id="mauticform_websitenewslettersubscription"
        data-mautic-form="websitenewslettersubscription"
        encType="multipart/form-data"
      >
        <div
          className="mauticform-error"
          id="mauticform_websitenewslettersubscription_error"
        ></div>
        <div
          className="mauticform-message"
          id="mauticform_websitenewslettersubscription_message"
        ></div>
        <div className="mauticform-innerform">
          <div
            className="mauticform-page-wrapper mauticform-page-1"
            data-mautic-form-page="1"
          >
            <div
              id="mauticform_websitenewslettersubscription_email_address"
              className="mauticform-row mauticform-email mauticform-field-1"
            >
              <label className="sr-only" htmlFor="email">
                Enter your email address
              </label>
              <input
                id="mauticform_input_websitenewslettersubscription_email_address"
                name="mauticform[email_address]"
                className="w-full text-gray-300 duration-100 bg-gray-800 border-none focus:ring-1 focus:ring-gray-300 placeholder-gray-275 font-display px-4 py-2.5 text-lg"
                type="email"
                required={true}
                placeholder={"Enter your email address"}
              />
            </div>

            <div
              id="mauticform_websitenewslettersubscription_gdpr_accepted"
              data-validate="gdpr_accepted"
              data-validation-type="radiogrp"
              className="flex max-w-sm gap-4 mt-4"
            >
              <input
                name="mauticform[gdpr_accepted]"
                className="text-orange-onDark focus:outline-none form-checkbox"
                id="mauticform_radiogrp_radio_gdpr_accepted_Yes0"
                type="checkbox"
                value="Yes"
                required={true}
              />
              <label
                className="text-xs text-gray-100 mauticform-label"
                htmlFor="mauticform_radiogrp_radio_gdpr_accepted_Yes0"
              >
                I consent to the use of my given e-mail address to receive
                communication and news about the Swarm project. Data will be
                controlled and processed by Swarm Foundation.
              </label>
            </div>

            <div
              id="mauticform_websitenewslettersubscription_i_consent_to_gathering_an"
              data-validate="i_consent_to_gathering_an"
              data-validation-type="radiogrp"
              className="flex max-w-sm gap-4 mt-4"
            >
              <input
                name="mauticform[i_consent_to_gathering_an]"
                className="text-orange-onDark focus:outline-none form-checkbox"
                id="mauticform_radiogrp_radio_i_consent_to_gathering_an_Yes0"
                type="checkbox"
                value="Yes"
                required={true}
              />
              <label
                className="text-xs mauticform-label"
                htmlFor="mauticform_radiogrp_radio_i_consent_to_gathering_an_Yes0"
              >
                I consent to the gathering and analysis of the data generated by
                my responses and clicks to the received communication and news
                for the purposes of better understanding and communicating with
                the Swarm user base. Data will be controlled and processed by
                Swarm Foundation.
              </label>
            </div>

            <button
              type="submit"
              name="mauticform[submit]"
              id="mauticform_input_websitenewslettersubscription_submit"
              value=""
              className="inline-flex items-center justify-center gap-2 px-4 py-2 mt-6 text-lg font-semibold tracking-wider uppercase transition duration-200 hover:bg-opacity-80 font-display group focus:outline-none focus:ring-4 focus:ring-opacity-50"
            >
              <span>Subscribe</span>
              <div className="relative w-4 h-4">
                <ArrowIcon className="absolute inset-0 w-4 h-4 duration-200 group-hover:translate-x-4 group-hover:opacity-0" />
                <ArrowIcon className="absolute inset-0 w-4 h-4 duration-200 -translate-x-4 opacity-0 group-hover:translate-x-0 group-hover:opacity-100" />
              </div>
            </button>
          </div>
        </div>

        <input
          type="hidden"
          name="mauticform[formId]"
          id="mauticform_websitenewslettersubscription_id"
          value="4"
        />
        <input
          type="hidden"
          name="mauticform[return]"
          id="mauticform_websitenewslettersubscription_return"
          value=""
        />
        <input
          type="hidden"
          name="mauticform[formName]"
          id="mauticform_websitenewslettersubscription_name"
          value="websitenewslettersubscription"
        />
      </form>
    </div>
    // <form className="flex flex-wrap justify-center w-full gap-4 lg:flex-nowrap">
    //   <label className="sr-only" htmlFor="email">
    //     Enter your email address
    //   </label>
    //   <InputField
    //     onChange={() => {}}
    //     value={""}
    //     placeholder="Enter your email address"
    //     type="email"
    //     name="email"
    //     className="px-4 py-2.5 text-lg flex-grow lg:w-full"
    //   />
    //   <Button
    //     title="Subscribe"
    //     arrow={true}
    //     href="/"
    //     background="transparent"
    //     color="gray"
    //   />
    // </form>
  );
};

export default Newsletter;
