name: "build-test"
on:
  push:
    branches:
      - add-swarm-actions

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: "12"

      - name: Install gulp
        run: npm install --global gulp-cli

      - name: Build
        run: |
          yarn
          yarn gulp

      - uses: ethersphere/swarm-actions/upload-dir@v0
        id: upload
        with:
          dir: ./dist
          index-document: index.html
          postage-batch-id: ${{ secrets.POSTAGE_BATCH_ID }}
          bee-url: ${{ secrets.BEE_URL }}
          timeout: 300000
          headers: |
            authorization: ${{ secrets.API_TOKEN }}

      - uses: ethersphere/swarm-actions/write-feed@v0
        id: feed
        with:
          reference: ${{ steps.upload.outputs.reference }}
          topic: "swarm-homepage-main"
          postage-batch-id: ${{ secrets.POSTAGE_BATCH_ID }}
          bee-url: ${{ secrets.BEE_URL }}
          signer: ${{ secrets.SIGNER }}
          headers: |
            authorization: ${{ secrets.API_TOKEN }}

      - uses: ethersphere/swarm-actions/reference-to-cid@v0
        id: cid
        with:
          reference: ${{ steps.feed.outputs.manifest }}

      - run: |
          echo 'Chunk Reference: ${{ steps.upload.outputs.reference }}'
          echo 'Feed Reference: ${{ steps.feed.outputs.reference }}'
          echo 'Feed Manifest: ${{ steps.feed.outputs.manifest }}'
          echo 'Feed Bzz.link: https://${{ steps.cid.outputs.cid }}.bzz.link'
